import { Box, Center, Flex, Stack, VStack } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { Footer } from '../components/layout/Footer'
import { NavBar } from '../components/layout/NavBar'

import { Hero } from '../components/sections/Hero'
import { About } from '../components/sections/About'
import { Pricing } from '../components/sections/Pricing'
import { Workout } from '../components/sections/Workouts'
import { CTA } from '../components/sections/CTA'
import { Testimonials } from '../components/sections/Testimonials'
import { FAQ } from '../components/sections/FAQ'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>GymME! - You Fit Here!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        direction="column"
        justifyContent="center"
        alignItems={"center"}
      >
        <Flex
          bg="neutral.500"
          w="100%"
          h="790px"
          flexDir={"column"}
          alignItems="center"
        >
          <Flex
            w="100%"
            flexDirection="column"
            alignItems="center"
          >
            <Hero />
          </Flex>

        </Flex>



        <About />

        <Workout />

        <Testimonials />

        <Pricing />

        <FAQ />

        <CTA />
        <Footer />
      </Flex>
    </>

  )
}

export default Home
